### ISSUE TITLE
Compilation error in child_process.ts

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rls-vscode#270]
```
[ts]
Argument of type '{ stdout: Buffer; stderr: Buffer; }' is not assignable to parameter of type 'ExecChildProcessResult<string> | PromiseLike<ExecChildProcessResult<string>> | undefined'.
  Type '{ stdout: Buffer; stderr: Buffer; }' is not assignable to type 'PromiseLike<ExecChildProcessResult<string>>'.
    Property 'then' is missing in type '{ stdout: Buffer; stderr: Buffer; }'.
```

Introduced in #253

**Comment by Xanewok** [comment]
It seems that the node typings are wrong?

For example the variants with args are: (notice the mismatch between function comments and stdout/stderr types)
```ts
    // `options` with `"buffer"` or `null` for `encoding` means stdout/stderr are definitely `Buffer`.
    export function execFile(file: string, options: { encoding: "buffer" | null } & ExecFileOptions, callback: (error: Error | null, stdout: string, stderr: string) => void): ChildProcess;
    export function execFile(file: string, args: string[] | undefined | null, options: { encoding: "buffer" | null } & ExecFileOptions, callback: (error: Error | null, stdout: string, stderr: string) => void): ChildProcess;

    // `options` with well known `encoding` means stdout/stderr are definitely `string`.
    export function execFile(file: string, options: { encoding: BufferEncoding } & ExecFileOptions, callback: (error: Error | null, stdout: Buffer, stderr: Buffer) => void): ChildProcess;
    export function execFile(file: string, args: string[] | undefined | null, options: { encoding: BufferEncoding } & ExecFileOptions, callback: (error: Error | null, stdout: Buffer, stderr: Buffer) => void): ChildProcess;
```

For args-less variant this is as expected, and we don't get an error there:

```ts
    // `options` with `"buffer"` or `null` for `encoding` means stdout/stderr are definitely `Buffer`.
    export function exec(command: string, options: { encoding: "buffer" | null } & ExecOptions, callback?: (error: Error | null, stdout: Buffer, stderr: Buffer) => void): ChildProcess;

    // `options` with well known `encoding` means stdout/stderr are definitely `string`.
    export function exec(command: string, options: { encoding: BufferEncoding } & ExecOptions, callback?: (error: Error | null, stdout: string, stderr: string) => void): ChildProcess;
```

This comes from my local `/home/xanewok/repos/rls_vscode/node_modules/@types/node/index.d.ts` path.

@kdy1 do we need to upgrade the typings?
Changing encoding orders like in #271 didn't fix the problem for me.

**Comment by Xanewok** [comment]
I am so confused. It seems that https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b66ac3815ab5a32808a10388c0f086bbe4d9a318 fixed this, so I tried to pull 8.0.32 node typings (from 3rd Oct 2017) into package.json and error went away while running `npm install && npm run compile` but removing said changes and running a clean install on current branch also stopped reporting any errors as well.
