### PR TITLE
Update @types/node to 8.0.32

### LINKED ISSUE #270: Compilation error in child_process.ts
```
[ts]
Argument of type '{ stdout: Buffer; stderr: Buffer; }' is not assignable to parameter of type 'ExecChildProcessResult<string> | PromiseLike<ExecChildProcessResult<string>> | undefined'.
  Type '{ stdout: Buffer; stderr: Buffer; }' is not assignable to type 'PromiseLike<ExecChildProcessResult<string>>'.
    Property 'then' is missing in type '{ stdout: Buffer; stderr: Buffer; }'.
```

Introduced in #253

### PR DESCRIPTION
**Pull request by Xanewok**
Fixes #270.
This fixes a ts compilation error, `execFile` types were fixed in https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b66ac3815ab5a32808a10388c0f086bbe4d9a318.

r? @nrc

cc @kdy1

### CODE REVIEW

**Comment by nrc** [comment]
Thanks!

**Comment by kdy1** [comment]
I'm not sure what to do because vscode on windows includes nodejs 7.9

`Help` -> `Information` 

```
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node7.9.0
Architecture x64
```


Additional note: When vscode updates node version to 8.x, `util.promisify` should be used instead of `new Promise`.

**Comment by kdy1** [comment]
Also note that `@types/node` is updated to `8.9.5` instead of `8.0.32`.

**Comment by Xanewok** [comment]
Ah dang it, you're right! I mostly focused on the changed integrity hash and didn't notice that the minor version changed as well :(
